### ISSUE TITLE
randomly losing connection to server, with no errors

### ISSUE THREAD

**Issue by Tigerboy007** [SalvieMundi/DefinitiveEditionVanillaPlus#46]

**Comment by SalvieMundi** [comment]
How often is it happening, and what are you doing when it happens? Only asking cuz it sounds like a client side issue, and I doubt I will find logs on the server.

If possible, zip up and send me everything in: 

C:/Program Files (x86)/Minecraft Launcher/Minecraft Definitive Edition/logs

**Comment by Tigerboy007** [comment]
oh hang on, this may be my fault, I forgot to apply more ram when you told me to do a full re-install

**Comment by SalvieMundi** [comment]
Nah, even if it's the RAM's fault (highly doubt), it is still a bug in the sense that I don't want anyone to need more than 4GB to play.

**Comment by Tigerboy007** [comment]
yeah it was the ram by the looks, still want the logs?

**Comment by SalvieMundi** [comment]
Yes definitely. I haven't been experiencing the random client kicks that you and Maru have, so I'm inclined to think the RAM isn't the real culprit, as I know I leave mine at 4GB and it rarely goes past 70% utilization. Increasing it may have a real effect or cause the issue to become less common since garbage collection doesn't need to be as aggressive, but I doubt it truly resolves the underlying issue.

**Comment by SalvieMundi** [comment]
[logs.zip](https://github.com/SalvieMundi/DefinitiveEditionVanillaPlus/files/7796593/logs.zip)

**Comment by SalvieMundi** [comment]
Culprit is almost certainly this line:

[15:11:36] [Render thread/ERROR]: missing entity for data tracking ClientWorld minecraft:overworld24445

Looks like an entity is missing a renderer, or some other form of nbt data. Pinning this on animals plus since half the other open issues are relating to it.

**Comment by SalvieMundi** [comment]
will be fixed in 1.0.7a
