### ISSUE TITLE
Cannot join server due to crab bucket

### ISSUE THREAD

**Issue by Tigerboy007** [SalvieMundi/DefinitiveEditionVanillaPlus#51]
![20220104_135140](https://user-images.githubusercontent.com/96267009/148069421-8d852bc5-1039-4d7b-8c36-27e8009ebdd8.jpg)

**Comment by Tigerboy007** [comment]
this was fixed by performing the update again
however I did then find these crabs with no texture, I was unable to replicate it though (only the pink and black crabs are natural spawns here
![20220104_140404](https://user-images.githubusercontent.com/96267009/148070944-6e0471e1-61ea-49cf-b053-fbba8af0e86f.jpg)
)

**Comment by Tigerboy007** [comment]
they're at x=618 y=836 on the server

**Comment by SalvieMundi** [comment]
So, to make sure I am understanding:

Initial issue was resolved after you installed the 1.0.7a download? That would be expected. The better animals plus mod responsible for those items was completely overhauled.

Then, after logging in, you encountered the black and pink crabs, which are actually textureless (using the black and pink "missing" texture)? I would expect that is due to the mod update, as well.

If that is all correct, I am going to close the issue. It means the BAP fixes worked. The textureless crabs are likely a result of the fix and why I want to wipe the world one more time before going public. I'd imagine there might also be other BAP mobs with similar, non-crashing issues.

Edit: to further clarify, the textureless crabs issue is because the mob spawned pre 1.0.7a, and then had to be rendered with the new fixes post 1.0.7a. This probably freaks the game out, and the actual fix for this and other BAP mobs spawned pre-1.0.7a is to actually just delete them from the server, this why I want to wipe it.

**Comment by Tigerboy007** [comment]
ahh yeah that makes sence with the second point
but for the first, I had already updated to the new version, and got that message, then I re- updated and it was all fine

**Comment by SalvieMundi** [comment]
Curious, did you "update client" the first time and then do a clean "install client" the second time?

**Comment by Tigerboy007** [comment]
nope, did update both times

**Comment by SalvieMundi** [comment]
Weird... I'm going to visit that spot on the server and if nothing happens to me, I'll close the ticket. It could be that the first time you tried to join, the server said, "what is crab_bucket?" And deleted the item after it kicked you. And the reinstall is a coincidence. Something similar happened after I joined. It kicked me, and on my test server console, it said "kicked SalveMundiProd, deleted unknown id tarantula_hair"

**Comment by Tigerboy007** [comment]
strange, maybe.
The location is unrelated to the first issue though

**Comment by Tigerboy007** [comment]
FIRST

**Comment by SalvieMundi** [comment]
Ah ok. Well, no sense in me going out there then. I'mma close this for now. If you see any more strangeness, just open a new ticket
